"""Shodan query dictionaries, keyed by family name, for each device category.

Moved out of kamerka/tasks.py verbatim (no query strings changed) so the
~400 lines of static data don't crowd out the actual task orchestration
logic. Re-exported by kamerka.tasks for backward compatibility.
"""

healthcare_queries = {"zoll": "http.favicon.hash:-236942626",
                      'dicom': "dicom",
                      "perioperative": "HoF Perioperative",
                      "wall_of_analytics": "title:'Wall of Analytics'",
                      "viztek_exa": "X-Super-Powered-By: VIZTEK EXA",
                      "medweb": "html:'DBA Medweb. All rights reserved.'",
                      "intuitim": "http.favicon.hash:159662640",
                      "medcon_archiving_system": "http.favicon.hash:-897903496",
                      "orthanc_explorer": "title:'Orthanc Explorer'",
                      "Marco Pacs": "title:'Marco pacs'",
                      "osirix": "title:OsiriX",
                      "clari_pacs": "title:ClariPACS",
                      "siste_lab": "http.html:SisteLAB",
                      "opalweb": "html:opalweb",
                      "neuropro": "title:'EEG Laboratory'",
                      "tmw_document_imaging": "title:'TMW Document Imaging'",
                      "erez": "title:'eRez Imaging'",
                      "gluco_care": "html:'GlucoCare igc'",
                      "glucose_guide": "title:'glucose guide'",
                      "grandmed_glucose": "title:'Grandmed Glucose'",
                      "philips_digital_pathology": "title:'Philips Digital Pathology'",
                      "tricore_pathology": "title:'TriCore Pathology'",
                      "appsmart_ophthalmology": "title:'Appsmart Ophthalmology'",
                      "chs_ophthalmology": "title:'CHS Ophthalmology'",
                      "ram_soft": "html:powerreader",
                      "xnat": "http.favicon.hash:-230640598",
                      "iris_emr": "title:'Iris EMR'",
                      "eclinicalworks_emr": "title:'Web EMR Login Page'",
                      "open_emr": "http.favicon.hash:1971268439",
                      "oscar_emr": "title:'OSCAR EMR'",
                      "wm_emr": "http.favicon.hash:1617804812",
                      "doctors_partner_emr": "title:'DoctorsPartner'",
                      "mckesson_radiology": "title:'McKesson Radiology'",
                      "kodak_carestream": "title:'Carestream PACS'",
                      "meded": "title:meded",
                      "centricity_radiology": "http.favicon.hash:-458315012",
                      "openeyes": "http.favicon.hash:-885931907",
                      "orthanc": "orthanc",
                      "horos": "http.favicon.hash:398467600",
                      "open_mrs": "title:openmrs",
                      "mirth_connect": "http.favicon.hash:1502215759",
                      "acuity_logic": "title:AcuityLogic",
                      "optical_coherence_tomography": "title:'OCT Webview'",
                      "philips_intellispace": "title:INTELLISPACE",
                      "vitrea_intelligence": "title:'Vitrea intelligence'",
                      "phenom_electron_microscope": "title:'Phenom-World'",
                      "meddream_dicom_viewer": "html:Softneta",
                      "merge_pacs": "http.favicon.hash:-74870968",
                      "synapse_3d": "http.favicon.hash:394706326",
                      "navify": "title:navify",
                      "telemis_tmp": "http.favicon.hash:220883165",
                      "brainlab": "title:'Brainlab Origin Server'",
                      "nexus360": "http.favicon.hash:125825464",
                      "brain_scope": "title:BrainScope",
                      "omero_microscopy": "http.favicon.hash:2140687598",
                      "meditech": "Meditech",
                      "cynetics": "cynetics",
                      "promed": "Promed",
                      "carestream": "Carestream",
                      "carestream_web": "title:Carestream",
                      "vet_rocket": "http.html:'Vet Rocket'",
                      "planmeca": "Planmeca",
                      "vet_view": "http.favicon.hash:1758472204",
                      "lumed": "http.html:'LUMED'",
                      "infinitt": "http.favicon.hash:-255936262",
                      "labtech": "labtech",
                      "progetti": "http.html:'Progetti S.r.l.'",
                      "qt_medical": "http.html:'QT Medical'",
                      "aspel": "ASPEL",
                      "huvitz_optometric": "http.html:'Huvitz'",
                      "optovue": "Optovue",
                      "optos_advance": "http.title:'OptosAdvance'",
                      "asthma_monitoring_adamm": "http.title:'HCO Telemedicine'",
                      "pregnabit": "http.html:'Pregnabit'",
                      "prime_clinical_systems": "http.html:'Prime Clinical Systems'",
                      "omni_explorer": "http.title:OmniExplorer",
                      "avizia": "http.html:'Avizia'",
                      "operamed": "Operamed",
                      "early_sense": "http.favicon.hash:-639764351",
                      "tunstall": "http.html:'Tunstall'",
                      "clini_net": "http.html:'CliniNet®'",
                      "intelesens": "title:'zensoronline)) - online monitoring'",
                      "kb_port": "http.html:'KbPort'",
                      "nursecall_message_service": "http.title:'N.M.S. - Nursecall Message Service'",
                      "image_information_systems": "http.html:'IMAGE Information Systems'",
                      "agilent_technologies": "Agilent Technologies port:5025",
                      "praxis_portal2": "http.html:'Medigration'",
                      "xero_viewer": "http.title:'XERO Viewer'"}

ics_queries = {"niagara": "port:1911,4911 product:Niagara",
               'bacnet': '"Instance ID:" "Object Name:"',
               'modbus': "Unit ID: 0",
               'siemens': 'Original Siemens Equipment Basic Firmware:',
               'dnp3': "port:20000 source address",
               "ethernetip": '"Product name:" "Vendor ID:"',
               "gestrip": 'port:18245,18246 product:"general electric"',
               'hart': "port:5094 hart-ip",
               'pcworx': "port:1962 PLC",
               "mitsubishi": "port:5006,5007 product:mitsubishi",
               "omron": "port:9600 response code",
               "redlion": 'port:789 product:"Red Lion Controls"',
               'codesys': 'product:"3S-Smart Software Solutions"',
               "iec": "port:2404 asdu address",
               'proconos': "port:20547 PLC",

               "plantvisor": "Server: CarelDataServer",
               "iologik": "iologik",
               "moxa": "Moxa",
               "akcp": "Server: AKCP Embedded Web Server",
               "spidercontrol": "powered by SpiderControl TM",
               "tank": "port:10001 tank",
               "iq3": "Server: IQ3",
               "is2": "IS2 Web Server",
               "vtscada": "Server: VTScada",
               'zworld': "Z-World Rabbit 200 OK",
               "nordex": "html:nordex",
               "sailor": 'title:Sailor title:VSAT',
               'nmea': "$GPGGA",

               "axc": "PLC Type: AXC",
               "modicon": "modicon",
               "xp277": "HMI, XP277",
               "vxworks": "vxworks",
               "eig": "EIG Embedded Web Server",
               "digi": "TransPort WR21",
               "windweb": "server: WindWeb",
               "moxahttp": "MoxaHttp",
               "lantronix": "lantronix",
               "entelitouch": "Server: DELTA enteliTOUCH",
               "energyict_rtu": "EnergyICT RTU",
               "crestron": "crestron",
               "saphir": 'Server: "Microsoft-WinCE" "Content-Length: 12581"',
               "ipc@chip": "IPC@CHIP",
               "addup": "addUPI",
               "anybus": '"anybus-s"',
               "windriver": "WindRiver-WebServer",
               "wago": "wago",
               "niagara_audit": "niagara_audit",
               "niagara_web_server": "Niagara Web Server",
               "trendnet": "trendnet",
               "stulz_klimatechnik": "Stulz GmbH Klimatechnik",
               "somfy": "title:Somfy",
               "scalance": "scalance",
               "simatic": "simatic",
               "simatic_s7": "Portal0000",
               "schneider_electric": "Schneider Electric",
               "power_measurement": "Power Measurement Ltd",
               "power_logic": "title:PowerLogic",
               "telemecanique_bxm": "TELEMECANIQUE BMX",
               "schneider_web": "Schneider-WEB",
               "fujitsu_serverview": "serverview",
               "eiportal": "eiPortal",
               "ilon": "i.LON",
               "webvisu": "Webvisu",
               "total_access": 'ta gen3 port:2000',
               "vantage_infusion": "http.html:'InFusion Controller'",
               "sensoteq": "title:'sensoteq'",
               "sicon-8": "sicon-8",
               "automation_direct_hmi": "Server: EA-HTTP/1.0",
               "flotrac": "FloTrac",
               "innotech_bms": "http.title:'Innotech BMS'",
               "skylog": "http.title:skylog",
               "miele@home": "title:Miele@home",
               "alphacom": "http.title:Alphacom",
               "simplex_grinnell": "http.html:SimplexGrinnell title:login",
               "bosch_security": "http.html:'Bosch Security'",

               "other_hmi": "html:hmiBody",
               "fronius": "title:fronius",
               "webview": "http.favicon.hash:207964650",
               "Siemens Sm@rtClient": "title:'Siemens Sm@rtClient'",
               "WAGO": "title:'wago ethernet'",
               "sensatronics": "html:sensatronics",
               "extron": "Extron Electronics",
               "mikrotik_streetlighs": "mikrotik streetlight",
               "kesseltronics": "Kesseltronics",
               "unitronics": "title:'Unitronics PLC'",
               "atvise": "Server: atvise",
               "clearSCADA": "ClearSCADA",
               "youless": "title:YouLess",
               "DLILPC": "DLILPC",
               "intelliSlot": "title:IntelliSlot",
               "temperature_monitor": "title:'Temperature Monitor' !title:avtech",
               "CirCarLife": "CirCarLife -ASUSTeK",
               "web_scada": "title:'web scada'",
               "kaco": "kaco",
               "indect_parkway": "title:indect",
               "intuitive_Controller": "http.favicon.hash:1434282111",
               "intuitive_controller_2": "http.favicon.hash:-1011909571",
               "homeLYnk": "homeLYnk",
               "APC": "Location: home.htm Content-Length: 0 WebServer",
               "netio": "title:netio",
               "asi_controls": "title:'ASI Controls'",
               "myscada": "title:myscada",
               "iB-COM": "title:iB-COM",
               "building_operation_webstation": "title:'building operation'",
               "ftp_scada": "scada login",
               "apc_ftp": "APC FTP server",
               "network_management_card": "Network Management Card",
               "wemo_insight": "Belkin WeMo",
               "connect_ups": "title:ConnectUPS",
               "upshttpd": "Server: upshttpd",
               "poweragent": "PowerAgent",
               "CS121": "title:'CS121 SNMP/Web Adapter'",
               "ab_ethernet": "cspv4",

               "climatix": "Siemens Building Technologies Climatix",
               "bas_scada": "BAS SCADA Service",
               "watt_router": "SOLAR controls product server",
               "doors": '"HID VertX" port:4070',
               "saferoads": "Saferoads VMS",
               "xzeres": 'title:"XZERES Wind"',
               "doorbird": "html:DoorBird",

               "jeedom": 'title:"Jeedom"',
               "pwrctrl": '"NET-PwrCtrl"',
               "heatmiser_thermostat": 'title:"Heatmiser Wifi Thermostat"',
               "xpanel": "title:xpanel",
               "c4_max": "[1m[35mWelcome on console",
               "universal_devices": "ucos",
               "dasdec": "dasdec",
               "brightsign": 'title:"BrightSign&reg;"',
               "leica": "title:leica title:interface",
               "hughesnet": "html:hughesnet",
               "skyline": "'server: skyline'",
               "beward_door": "'DS06A(P) SIP Door Station'",
               "wallbox": "title:wallbox",
               "acadia": "acadia",
               "walchem": "html:walchem",
               "gnss": "'NTRIP' 'SOURCETABLE'",
               "traccar": "title:traccar",
               "trimble": 'html:"trimble Navigation"',
               "spacelynk": "title:spaceLYnk",
               }

coordinates_queries = {"videoiq": 'title:"VideoIQ Camera Login"',
                       "hikvision":'product:"Hikvision IP Camera"',
                       "webcam": "device:webcam",
                       "webcamxp": "webcamxp",
                       "vivotek": "vivotek",
                       "netwave": 'product:"Netwave IP camera http config"',
                       "techwin": "techwin",
                       "lutron": 'html:<h1>LUTRON</h1>',
                       "mobotix": "mobotix",
                       "iqinvision": "iqinvision",
                       "grandstream": 'ssl:"Grandstream" "Set-Cookie: TRACKID"',
                       "amcrest": 'html:"@WebVersion@" html:amcrest',
                       "contec": '"content/smarthome.php"',
                       'printer': "device:printer",
                       'mqtt': 'product:mqtt',
                       'rtsp': "port:'554'",
                       "ipcamera": "IPCamera_Logo",
                       "yawcam": "yawcam",
                       "blueiris": "http.favicon.hash:-520888198",
                       'ubnt': "UBNT Streaming Server",
                       "go1984": "go1984",
                       "dlink": "Server: Camera Web Server",
                       "avtech": "linux upnp avtech",
                       "adh": "ADH-web",
                       "axis": 'http.title:"axis" http.html:live',
                       "rdp": "has_screenshot:true port:3389",
                       "vnc": "has_screenthos:true port:5901",
                       "screenshot": "has_screenshot:true !port:3389 !port:3388 !port:5900",
                       "bbvs": "Server: BBVS",
                       "baudisch": "http.favicon.hash:746882768",
                       "loxone_intercom": "title:'Loxone Intercom Video'",

                       "idss": "Intelligent Digital Security System",
                       "webiopi": 'webiopi 200 ok',
                       "iobroker": "ioBroker.admin",
                       "comelit": "html:comelit",

                       "niagara": "port:1911,4911 product:Niagara",
                       'bacnet': '"Instance ID:" "Object Name:"',
                       'modbus': "Unit ID: 0",
                       'siemens': 'Original Siemens Equipment Basic Firmware:',
                       'dnp3': "port:20000 source address",
                       "ethernetip": '"Product name:" "Vendor ID:"',
                       "gestrip": 'port:18245,18246 product:"general electric"',
                       'hart': "port:5094 hart-ip",
                       'pcworx': "port:1962 PLC",
                       "mitsubishi": "port:5006,5007 product:mitsubishi",
                       "omron": "port:9600 response code",
                       "redlion": 'port:789 product:"Red Lion Controls"',
                       'codesys': "port:2455 operating system",
                       "iec": "port:2404 asdu address",
                       'proconos': "port:20547 PLC",

                       "plantvisor": "Server: CarelDataServer",
                       "iologik": "iologik",
                       "moxa": "Moxa",
                       "akcp": "Server: AKCP Embedded Web Server",
                       "spidercontrol": "powered by SpiderControl TM",
                       "tank": "port:10001 tank",
                       "iq3": "Server: IQ3",
                       "is2": "IS2 Web Server",
                       "vtscada": "Server: VTScada",
                       'zworld': "Z-World Rabbit",
                       "nordex": "html:nordex",

                       "axc": "PLC Type: AXC",
                       "modicon": "modicon",
                       "xp277": "HMI, XP277",
                       "vxworks": "vxworks",
                       "eig": "EIG Embedded Web Server",
                       "digi": "TransPort WR21",
                       "windweb": "server: WindWeb",
                       "moxahttp": "MoxaHttp",
                       "lantronix": "lantronix",
                       "entelitouch": "Server: DELTA enteliTOUCH",
                       "energyict_rtu": "EnergyICT RTU",
                       "crestron": "crestron",
                       "wince": 'Server: "Microsoft-WinCE"',
                       "ipc@chip": "IPC@CHIP",
                       "addup": "addUPI",
                       "anybus": '"anybus-s"',
                       "windriver": "WindRiver-WebServer",
                       "wago": "wago",
                       "niagara_audit": "niagara_audit",
                       "niagara_web_server": "Niagara Web Server",
                       "trendnet": "trendnet",
                       "stulz_klimatechnik": "Stulz GmbH Klimatechnik",
                       "somfy": "title:Somfy",
                       "scalance": "scalance",
                       "simatic": "simatic",
                       "simatic_s7": "Portal0000",
                       "schneider_electric": "Schneider Electric",
                       "power_measurement": "Power Measurement Ltd",
                       "power_logic": "title:PowerLogic",
                       "telemecanique_bxm": "TELEMECANIQUE BMX",
                       "schneider_web": "Schneider-WEB",
                       "fujitsu_serverview": "serverview",
                       "eiportal": "eiPortal",
                       "ilon": "i.LON",
                       "Webvisu": "Webvisu",
                       "total_access": 'ta gen3 port:2000',
                       "vantage_infusion": "http.html:'InFusion Controller'",
                       "sensoteq": "title:'sensoteq'",
                       "sicon-8": "sicon-8",
                       "automation_direct_hmi": "Server: EA-HTTP/1.0",
                       "flotrac": "FloTrac",
                       "innotech_bms": "http.title:'Innotech BMS'",
                       "skylog": "http.title:skylog",
                       "miele@home": "title:Miele@home",
                       "alphacom": "http.title:Alphacom",
                       "simplex_grinnell": "http.html:SimplexGrinnell title:login",
                       "bosch_security": "http.html:'Bosch Security'",

                       "fronius": "title:fronius",
                       "webview": "http.favicon.hash:207964650",
                       "siemens_Sm@rtClient": "title:'Siemens Sm@rtClient'",
                       "WAGO": "title:'wago ethernet'",
                       "sensatronics": "html:sensatronics",
                       "extron": "Extron Electronics",
                       "mikrotik_streetlighs": "mikrotik streetlight",
                       "kesseltronics": "Kesseltronics",
                       "unitronics": "title:'Unitronics PLC'",
                       "atvise": "Server: atvise",
                       "clearSCADA": "ClearSCADA",
                       "youless": "title:YouLess",
                       "DLILPC": "DLILPC",
                       "intelliSlot": "title:IntelliSlot",
                       "temperature_monitor": "title:'Temperature Monitor' !title:avtech",
                       "CirCarLife": "CirCarLife",
                       "web_scada": "title:'web scada'",
                       "kaco": "kaco",
                       "indect_parkway": "title:indect",
                       "intuitive_Controller": "http.favicon.hash:1434282111",
                       "intuitive_controller_2": "http.favicon.hash:-1011909571",
                       "homeLYnk": "homeLYnk",
                       "APC": "Location: home.htm Content-Length: 0 WebServer",
                       "netio": "title:netio",
                       "asi_controls": "title:'ASI Controls'",
                       "myscada": "title:myscada",
                       "iB-COM": "title:iB-COM",
                       "building_operation_webstation": "title:'building operation'",
                       "ftp_scada": "scada login",

                       "apc_ftp": "APC FTP server",
                       "network_management_card": "Network Management Card",
                       "wemo_insight": "Belkin WeMo",
                       "connect_ups": "title:ConnectUPS",
                       "upshttpd": "Server: upshttpd",
                       "poweragent": "PowerAgent",
                       "CS121": "title:'CS121 SNMP/Web Adapter'",
                       "ab_ethernet": "cspv4",

                       "climatix": "Siemens Building Technologies Climatix",
                       "bas_scada": "BAS SCADA Service",
                       "watt_router": "SOLAR controls product server",
                       "doors": '"HID VertX" port:4070',
                       "saferoads": "Saferoads VMS",
                       "xzeres": 'title:"XZERES Wind"',
                       "doorbird": "html:DoorBird",

                       "jeedom": 'title:"Jeedom"',
                       "pwrctrl": "NET-PwrCtrl",
                       "heatmiser_thermostat": 'title:"Heatmiser Wifi Thermostat"',
                       "xpanel": "title:xpanel",
                       "c4_max": "[1m[35mWelcome on console",
                       "universal_devices": "ucos",
                       "dasdec": "dasdec",
                       "brightsign": 'title:"BrightSign&reg;"',
                       "leica": "title:leica title:interface",
                       "hughesnet": "html:hughesnet",
                       "skyline": "server: skyline",
                       "beward_door": "DS06A(P) SIP Door Station",
                       "wallbox": "http.title:wallbox",
                       "acadia": "acadia",
                       "walchem": "html:walchem",
                       "GNSS": "NTRIP" "SOURCETABLE",
                       "traccar": "title:traccar",
                       "trimble": 'html:"trimble Navigation"',
                       "spacelynk": "title:spaceLYnk",
                       }

attackers_infra_queries = {"cobaltstrike": 'product:"Cobalt Strike Beacon"',
                           "msf": 'ssl:MetasploitSelfSignedCA',
                           # NOTE: this query uses smart/curly quotes (”) around "Covenant" and
                           # "Blazor". Shodan's query syntax only understands straight quotes ("...")
                           # for exact-phrase matching, so as written this query is not doing an exact
                           # phrase match the way the other quoted queries in this file do. Left as-is
                           # per the request to only fix if trivial to avoid changing match behavior
                           # for a query in active use without being able to verify results.
                           "covenant": 'ssl:”Covenant” http.component:”Blazor”',
                           "mythic": 'ssl:"Mythic" port:7443',
                           "bruteratel": "http.html_hash:-1957161625",
                           }
