"""
Django settings for kamerka project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set DJANGO_SECRET_KEY in the environment for a stable key. When it is not set
# a random key is generated at startup (sessions will not persist across
# restarts), which keeps the previously hardcoded key out of source control.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or get_random_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
# Off by default; set DJANGO_DEBUG=1 in the environment for local development.
DEBUG = _env_bool('DJANGO_DEBUG', False)

# Comma-separated list of allowed hosts, e.g. "example.com,www.example.com".
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]

# Where unauthenticated users are redirected. The Django admin login is used
# since the project already enables the admin app.
LOGIN_URL = '/admin/login/'

# Active Nmap scanning and exploitation (see app_kamerka.views.scan_dev /
# exploit_dev) reach out to and, in some cases (e.g. the Hikvision PoC),
# mutate real third-party devices. Both are OFF by default; set
# KAMERKA_ENABLE_ACTIVE_SCAN=1 / KAMERKA_ENABLE_EXPLOITATION=1 in the
# environment to opt in.
KAMERKA_ENABLE_ACTIVE_SCAN = _env_bool('KAMERKA_ENABLE_ACTIVE_SCAN', False)
KAMERKA_ENABLE_EXPLOITATION = _env_bool('KAMERKA_ENABLE_EXPLOITATION', False)

# Extra hardening that is only safe to enable once the app is served over HTTPS
# behind a real host, i.e. when DEBUG is off.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

# CELERY STUFF
# Celery 5's app.config_from_object(..., namespace='CELERY') (see
# kamerka/celery.py) expects every setting here to be uppercase and
# CELERY_-prefixed -- BROKER_URL (the old, un-namespaced Celery 3/4 form) is
# silently ignored by Celery 5+, so it is renamed to CELERY_BROKER_URL.
CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Nairobi'
CELERY_IMPORTS = ('kamerka.tasks',)
# scan_task/exploit_task (active Nmap scanning and exploitation probes) are
# pinned to a dedicated 'active' queue via @shared_task(queue='active') in
# kamerka/tasks.py. That lets a deployment run a separate worker consuming
# only the 'active' queue -- e.g. `celery -A kamerka worker -Q active` -- on
# network-isolated infrastructure, while the default worker (`celery -A
# kamerka worker -Q celery`) handles everything else (shodan_search,
# devices_nearby, whoisxml, etc). CELERY_TASK_ROUTES is left commented out
# below as the alternative way to assign queues (by task name, without
# touching the decorator) in case a deployment prefers to route tasks this
# way instead:
# CELERY_TASK_ROUTES = {
#     'kamerka.tasks.scan_task': {'queue': 'active'},
#     'kamerka.tasks.exploit_task': {'queue': 'active'},
# }
# Celery 6 will require the worker to explicitly opt in to retrying its
# initial broker connection on startup; set it now to silence the
# deprecation warning under Celery 5.
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
# Application definition
STATIC_URL = '/static/'
MEDIA_URL = '/scans/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'scans')
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app_kamerka',
    "celery_progress"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Requires authentication for all application views (see app_kamerka/middleware.py).
    'app_kamerka.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'kamerka.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kamerka.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

# USE_L10N was removed in Django 5.0 (localized formatting is always on since
# Django 4.0), so it is intentionally left unset here for forward compat.

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# Default primary key field type. Explicit so `makemigrations` on Django 3.2+
# does not warn/prompt about the implicit-pk-type change.
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Minimal logging config: a console handler at INFO so the print()-replacing
# logger.info/warning/exception calls throughout app_kamerka/views.py and
# kamerka/tasks.py still show up when running the dev server or a celery
# worker, instead of being silently dropped by Django's default logging
# config (which only surfaces WARNING+ on django.request/django.server).
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '%(asctime)s %(levelname)s %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'INFO',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
