# Generated by Django 4.2.13 on 2026-09-25 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_kamerka", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="twitternearby",
            name="device",
        ),
        migrations.DeleteModel(
            name="FlickrNearby",
        ),
        migrations.DeleteModel(
            name="TwitterNearby",
        ),
    ]
