# Generated by Django 4.2.13 on 2026-09-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_kamerka",
            "0002_remove_twitternearby_device_delete_flickrnearby_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="honeypot_reasons",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="device",
            name="honeypot_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="device",
            name="honeyscore",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
