# Generated by Django 4.2.13 on 2026-09-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_kamerka", "0003_device_honeypot_reasons_device_honeypot_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("reviewed", "Reviewed"),
                    ("confirmed", "Confirmed"),
                    ("false_positive", "False positive"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="suspected_false_positive",
            field=models.BooleanField(default=False),
        ),
    ]
