# Generated by Django 4.2.13 on 2026-09-26 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_kamerka", "0004_device_status_device_suspected_false_positive"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("scan", "Active scan"),
                            ("exploit", "Exploit attempt"),
                            ("honeyscore", "Shodan HoneyScore check"),
                            ("set_status", "Set device status"),
                            ("update_coordinates", "Update coordinates"),
                            ("whois", "Whois lookup"),
                            ("shodan_scan", "Shodan scan"),
                            ("binaryedge", "BinaryEdge score lookup"),
                            ("nearby", "Nearby devices search"),
                            ("notes", "Notes update"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target", models.CharField(blank=True, default="", max_length=255)),
                ("detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_kamerka.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
