# Generated by Django 4.2.13 on 2026-09-26 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_kamerka", "0005_auditlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={
                "permissions": [
                    ("view_capability", "Can view read-only pages and passive lookups"),
                    (
                        "run_search",
                        "Can run passive Shodan searches and enrichment/triage/export",
                    ),
                    ("active_scan", "Can run active Nmap scans"),
                    ("exploit", "Can run exploitation modules"),
                    ("administer", "Can administer scan scopes and users"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("scan", "Active scan"),
                    ("exploit", "Exploit attempt"),
                    ("honeyscore", "Shodan HoneyScore check"),
                    ("set_status", "Set device status"),
                    ("update_coordinates", "Update coordinates"),
                    ("whois", "Whois lookup"),
                    ("shodan_scan", "Shodan scan"),
                    ("binaryedge", "BinaryEdge score lookup"),
                    ("nearby", "Nearby devices search"),
                    ("notes", "Notes update"),
                    ("capability_denied", "Capability denied"),
                    ("scope_denied", "Target scope denied"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ScanAuthorization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short label, e.g. the engagement name.",
                        max_length=200,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional reference, e.g. an incident/engagement ticket id.",
                        max_length=200,
                    ),
                ),
                (
                    "cidr",
                    models.CharField(
                        help_text="An IPv4/IPv6 network (e.g. 203.0.113.0/24) or a single host (e.g. 203.0.113.5).",
                        max_length=100,
                    ),
                ),
                (
                    "allow_port_scan",
                    models.BooleanField(
                        default=False, help_text="Authorizes active Nmap scanning."
                    ),
                ),
                (
                    "allow_exploit",
                    models.BooleanField(
                        default=False, help_text="Authorizes exploitation attempts."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank for a scope that never expires.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
