# Generated by Django 5.2.17 on 2026-09-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kamerka', '0011_exploit_result_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralTaskResultAccess',
            fields=[
                ('task_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
