# Generated by Django 5.2.17 on 2026-09-26 13:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kamerka', '0012_generaltaskresultaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('scan', 'Scan'), ('exploit', 'Exploit')], max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='queued', max_length=16)),
                ('authorization_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('target_ip', models.CharField(max_length=100)),
                ('target_port', models.CharField(max_length=10)),
                ('target_type', models.CharField(max_length=100)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_operations', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='app_kamerka.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
