# Generated by Django 5.2.17 on 2026-09-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kamerka', '0013_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('scan', 'Active scan'), ('exploit', 'Exploit attempt'), ('honeyscore', 'Shodan HoneyScore check'), ('set_status', 'Set device status'), ('update_coordinates', 'Update coordinates'), ('whois', 'Whois lookup'), ('shodan_scan', 'Shodan scan'), ('binaryedge', 'BinaryEdge score lookup'), ('nearby', 'Nearby devices search'), ('notes', 'Notes update'), ('capability_denied', 'Capability denied'), ('scope_denied', 'Target scope denied'), ('operation_queued', 'Active operation queued')], max_length=50),
        ),
    ]
